# ZT notes:
# generated by GPT-5 mini


import os
from datetime import date
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

def fetch_prices(start="2025-07-01"):

    tickers = {"Gold": "GC=F", "Silver": "SI=F"}
    # yfinance allows downloading multiple tickers
    df = yf.download(list(tickers.values()), start=start, progress=False)
    # `Adj Close` is preferred for closing prices; fallback to `Close`
    if ("Adj Close" in df.columns.get_level_values(0)):
        adj = df["Adj Close"].copy()
    else:
        adj = df["Close"].copy()
    # rename columns to readable names
    col_map = {v: k for k, v in tickers.items()}
    adj = adj.rename(columns=col_map)
    return adj


def plot_series(df: pd.DataFrame, out_png: str):
    plt.style.use("ggplot")
    fig, ax = plt.subplots(figsize=(11, 5))
    # Plot Gold on left axis
    if "Gold" in df.columns:
        ax.plot(df.index, df["Gold"], label="Gold", color="gold", lw=1.5)
    ax.set_xlabel("Date")
    ax.set_ylabel("Gold Price (USD)", color="gold")
    ax.tick_params(axis="y", labelcolor="gold")

    # Plot Silver on right axis
    ax2 = ax.twinx()
    if "Silver" in df.columns:
        ax2.plot(df.index, df["Silver"], label="Silver", color="gray", lw=1.5)
    ax2.set_ylabel("Silver Price (USD)", color="gray")
    ax2.tick_params(axis="y", labelcolor="gray")

    ax.set_title("Daily Gold and Silver Prices")
    # combine legends
    lines, labels = ax.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    if lines or lines2:
        ax.legend(lines + lines2, labels + labels2, loc="upper left")

    fig.tight_layout()
    fig.savefig(out_png, dpi=150)
    plt.close(fig)


def main():
    start_date = "2025-07-01"
    df = fetch_prices(start=start_date) # it does not mention the end date
    out_dir = os.path.join(os.getcwd(), "data_example")
    os.makedirs(out_dir, exist_ok=True)
    csv_path = os.path.join(out_dir, "gold_silver.csv")
    png_path = os.path.join(out_dir, "gold_silver.png")
    df.to_csv(csv_path)
    plot_series(df, png_path)
    print(f"Saved CSV: {csv_path}")
    print(f"Saved plot: {png_path}")


if __name__ == "__main__":
    main()
